"""empty message

Revision ID: 80e93968b1a1
Revises: a32cb528d162
Create Date: 2020-08-24 23:06:08.247397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e93968b1a1'
down_revision = 'a32cb528d162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flights_airline_code', table_name='flights')
    op.create_index(op.f('ix_flights_airline_code'), 'flights', ['airline_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_airline_code'), table_name='flights')
    op.create_index('ix_flights_airline_code', 'flights', ['airline_code'], unique=True)
    # ### end Alembic commands ###
