"""initial migration

Revision ID: b5df6fca8cf4
Revises: 
Create Date: 2020-08-23 21:28:28.903399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5df6fca8cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('airline_code', sa.String(length=20), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('departure_port', sa.String(length=5), nullable=False),
    sa.Column('arrival_port', sa.String(length=5), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_airline_code'), 'flights', ['airline_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_airline_code'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
